### PR TITLE
Travisbrown topic/dotty cross build

### PR DESCRIPTION
**Pull request by LukaJCB**

### CODE REVIEW

**Comment by travisbrown** [comment]
@LukaJCB Do you mind if I rebase this branch manually to keep things clean and then cherry-pick your cats-free commit onto it?

**Comment by LukaJCB** [comment]
Not at all

**Comment by LukaJCB** [comment]
The merge wasn't entirely trivial, had to add a few things here and there just fyi

**Comment by travisbrown** [comment]
@LukaJCB Looking at this now, and I'm also going to rerun the Simulacrum Scalafix process, since there are some significant changes since this original experiment (like [footers](https://github.com/typelevel/simulacrum-scalafix/pull/8)).

**Comment by LukaJCB** [comment]
Oh cool, yeah I reran it to get the tests working since we've added methods to some typeclasses (like `zipAll` in align)

**Comment by travisbrown** [comment]
@LukaJCB :+1: I also just published a new release: https://github.com/typelevel/simulacrum-scalafix/releases/tag/v0.2.0

One annoying thing is that the footers cause "unmoored doc comment" warnings in Scaladoc [because we have `-Xlint` enabled](https://github.com/scala/scala/pull/2396), but it seems reasonable to avoid that by disabling `-Xlint` in the `(ScalaUnidoc, unidoc)` scope.

I'm hoping to have the updated branch ready this afternoon.

**Pull request closed without merging**
